declare namespace NodeJS {
  export interface ProcessEnv {
    REACT_APP_KAKAO_KEY: string
    REACT_APP_FIREBASE_API_KEY: string
    REACT_APP_FIREBASE_AUTH_DOMAIN: string
    REACT_APP_FIREBASE_DATABASE_URL: string
    REACT_APP_FIREBASE_PROJECT_ID: string
    REACT_APP_FIREBASE_STORAGEBUCKET: string
    REACT_APP_FIREBASE_MESSEING_SENDER_ID: string
    REACT_APP_FIREBASE_APP_ID: string
  }
}